# permissions for end users to edit xcpngclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-xcpng
    app.kubernetes.io/managed-by: kustomize
  name: xcpngcluster-editor-role
rules:
- apiGroups:
  - infrastructure.xcpng.k8s.io
  resources:
  - xcpngclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.xcpng.k8s.io
  resources:
  - xcpngclusters/status
  verbs:
  - get
