# permissions for end users to view xcpngmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-xcpng
    app.kubernetes.io/managed-by: kustomize
  name: xcpngmachine-viewer-role
rules:
- apiGroups:
  - infrastructure.xcpng.k8s.io
  resources:
  - xcpngmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.xcpng.k8s.io
  resources:
  - xcpngmachines/status
  verbs:
  - get
